### ISSUE TITLE
Is this cookbook used?

### ISSUE THREAD

**Issue by spuder** [galenemery/win2012r2#1]
Found this cookbook on accident. Is it in use? 

I notice that there is a password in the cookbook that might not want to be shared publicly.

**Comment by galenemery** [comment]
I need to set up better github notifications.  Sorry about the delay.

I created this as a demonstration cookbook.  The password in there is totally random and not used in the real world.

As time goes on, I'll be adding snippets to this cookbook, which will be demonstrating various functionality of Chef.
